// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./internal/services/models.js";

/**
 * @param {string} title
 * @param {string} description
 * @returns {$CancellablePromise<models$0.Article | null>}
 */
export function CreateArticle(title, description) {
    return $Call.ByID(808668729, title, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} category
 * @param {string} label
 * @returns {$CancellablePromise<services$0.LookupItem | null>}
 */
export function CreateLookup(category, label) {
    return $Call.ByID(1905389291, category, label).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} category
 * @param {string} label
 * @returns {$CancellablePromise<services$0.TraitItem | null>}
 */
export function CreateTrait(category, label) {
    return $Call.ByID(186843787, category, label).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAffiliation(id) {
    return $Call.ByID(2694748740, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteArticle(id) {
    return $Call.ByID(4207341624, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCharacter(id) {
    return $Call.ByID(2888080821, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFaction(id) {
    return $Call.ByID(3079450750, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLocation(id) {
    return $Call.ByID(2065392417, id);
}

/**
 * @param {number} id
 * @param {string} category
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLookup(id, category) {
    return $Call.ByID(3523028260, id, category);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLore(id) {
    return $Call.ByID(1869763510, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLoreCategory(id) {
    return $Call.ByID(3021652334, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRelationship(id) {
    return $Call.ByID(1350186120, id);
}

/**
 * @param {string} category
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTrait(category, id) {
    return $Call.ByID(4035375038, category, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Affiliation | null>}
 */
export function FetchAffiliation(id) {
    return $Call.ByID(390212899, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Affiliation[]>}
 */
export function FetchAllAffiliations() {
    return $Call.ByID(3101345105).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Article[]>}
 */
export function FetchAllArticles() {
    return $Call.ByID(1341597461).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<models$0.Character[]>}
 */
export function FetchAllCharacters(limit) {
    return $Call.ByID(3079915262, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Faction[]>}
 */
export function FetchAllFactions() {
    return $Call.ByID(1507432227).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Location[]>}
 */
export function FetchAllLocations() {
    return $Call.ByID(1722497314).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} category
 * @returns {$CancellablePromise<services$0.LookupItem[]>}
 */
export function FetchAllLookup(category) {
    return $Call.ByID(1192268800, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Lore[]>}
 */
export function FetchAllLore() {
    return $Call.ByID(1480822490).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} category
 * @returns {$CancellablePromise<services$0.TraitItem[]>}
 */
export function FetchAllTraits(category) {
    return $Call.ByID(758023059, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Article | null>}
 */
export function FetchArticle(id) {
    return $Call.ByID(4290365515, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.LoreCategory[]>}
 */
export function FetchCategories() {
    return $Call.ByID(1147202407).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Character | null>}
 */
export function FetchCharacter(id) {
    return $Call.ByID(2195128362, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Lore[]>}
 */
export function FetchCharacterLore(id) {
    return $Call.ByID(3290945214, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Relationship[]>}
 */
export function FetchCharacterRelationships(id) {
    return $Call.ByID(2047072793, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Faction | null>}
 */
export function FetchFaction(id) {
    return $Call.ByID(26663597, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Lore[]>}
 */
export function FetchGeneralLore() {
    return $Call.ByID(3493201601).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Location | null>}
 */
export function FetchLocation(id) {
    return $Call.ByID(3420735404, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @param {number} id
 * @param {string} category
 * @returns {$CancellablePromise<services$0.LookupItem | null>}
 */
export function FetchLookup(id, category) {
    return $Call.ByID(3984870629, id, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Lore | null>}
 */
export function FetchLore(id) {
    return $Call.ByID(3522502387, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Lore[]>}
 */
export function FetchLoreByCategory(id) {
    return $Call.ByID(1076841158, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Relationship | null>}
 */
export function FetchRelationship(id) {
    return $Call.ByID(2543099177, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Location[]>}
 */
export function FetchTopLevelLocations() {
    return $Call.ByID(4239849836).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} category
 * @param {number} id
 * @returns {$CancellablePromise<services$0.TraitItem | null>}
 */
export function FetchTrait(category, id) {
    return $Call.ByID(1332298489, category, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Open window editor based on the section
 * @param {string} section
 * @returns {$CancellablePromise<void>}
 */
export function OpenEditorWindow(section) {
    return $Call.ByID(3821903224, section);
}

/**
 * @param {models$0.Affiliation} affiliation
 * @returns {$CancellablePromise<models$0.Affiliation | null>}
 */
export function SaveAffiliation(affiliation) {
    return $Call.ByID(610365070, affiliation).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {models$0.Character} char
 * @returns {$CancellablePromise<models$0.Character | null>}
 */
export function SaveCharacter(char) {
    return $Call.ByID(1988835663, char).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {models$0.Faction} faction
 * @returns {$CancellablePromise<models$0.Faction | null>}
 */
export function SaveFaction(faction) {
    return $Call.ByID(801287184, faction).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @param {models$0.Location} location
 * @returns {$CancellablePromise<models$0.Location | null>}
 */
export function SaveLocation(location) {
    return $Call.ByID(1455493271, location).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @param {number} id
 * @param {string} label
 * @param {string} category
 * @returns {$CancellablePromise<services$0.LookupItem | null>}
 */
export function SaveLookup(id, label, category) {
    return $Call.ByID(3052816934, id, label, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {models$0.Lore} lore
 * @returns {$CancellablePromise<models$0.Lore | null>}
 */
export function SaveLore(lore) {
    return $Call.ByID(462985252, lore).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @param {number} id
 * @param {string} label
 * @returns {$CancellablePromise<models$0.LoreCategory | null>}
 */
export function SaveLoreCategory(id, label) {
    return $Call.ByID(3842817276, id, label).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * @param {models$0.Relationship} relationship
 * @returns {$CancellablePromise<models$0.Relationship | null>}
 */
export function SaveRelationships(relationship) {
    return $Call.ByID(2289153463, relationship).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @param {number} id
 * @param {string} label
 * @param {string} category
 * @returns {$CancellablePromise<services$0.TraitItem | null>}
 */
export function SaveTrait(id, label, category) {
    return $Call.ByID(1236566724, id, label, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {number} id
 * @param {string} title
 * @param {string} description
 * @returns {$CancellablePromise<models$0.Article | null>}
 */
export function UpdateArticle(id, title, description) {
    return $Call.ByID(3751245430, id, title, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Article.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = services$0.LookupItem.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = services$0.TraitItem.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.Affiliation.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType6);
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = models$0.Character.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = models$0.Faction.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = models$0.Location.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $Create.Array($$createType2);
const $$createType17 = models$0.Lore.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($$createType4);
const $$createType20 = models$0.LoreCategory.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $Create.Nullable($$createType10);
const $$createType23 = models$0.Relationship.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $Create.Nullable($$createType12);
const $$createType26 = $Create.Nullable($$createType14);
const $$createType27 = $Create.Nullable($$createType17);
const $$createType28 = $Create.Nullable($$createType23);
const $$createType29 = $Create.Nullable($$createType20);
