// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Affiliation {
    /**
     * Creates a new Affiliation instance.
     * @param {Partial<Affiliation>} [$$source = {}] - The source object to create the Affiliation.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Free to call themselves however they want, no 'type' table necessary, for ease of storytelling
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["faction_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Faction | null | undefined}
             */
            this["faction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Affiliation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Affiliation}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("faction" in $$parsedSource) {
            $$parsedSource["faction"] = $$createField5_0($$parsedSource["faction"]);
        }
        return new Affiliation(/** @type {Partial<Affiliation>} */($$parsedSource));
    }
}

export class Alignment {
    /**
     * Creates a new Alignment instance.
     * @param {Partial<Alignment>} [$$source = {}] - The source object to create the Alignment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Alignment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Alignment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Alignment(/** @type {Partial<Alignment>} */($$parsedSource));
    }
}

export class Article {
    /**
     * Creates a new Article instance.
     * @param {Partial<Article>} [$$source = {}] - The source object to create the Article.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tags"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["createdAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["updatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Article instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Article}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $Create.DateFromTime;
        const $$createField6_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("createdAt" in $$parsedSource) {
            $$parsedSource["createdAt"] = $$createField5_0($$parsedSource["createdAt"]);
        }
        if ("updatedAt" in $$parsedSource) {
            $$parsedSource["updatedAt"] = $$createField6_0($$parsedSource["updatedAt"]);
        }
        return new Article(/** @type {Partial<Article>} */($$parsedSource));
    }
}

export class Character {
    /**
     * Creates a new Character instance.
     * @param {Partial<Character>} [$$source = {}] - The source object to create the Character.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("firstname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["firstname"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["middlename"] = undefined;
        }
        if (!("surname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surname"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * e.g. "The Iron Hound"
             * @member
             * @type {string | undefined}
             */
            this["nickname"] = undefined;
        }
        if (!("age" in $$source)) {
            /**
             * Basic Identity & Status
             * String for "Unknown", "240", "Ageless"
             * @member
             * @type {string}
             */
            this["age"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Image path or URL
             * @member
             * @type {string | undefined}
             */
            this["portrait"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["goals"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Foreign Keys for Single-Choice Lookups (Nullable pointers if optional)
             * Example for me and my smooth brain : GenderID = (in SQL) gender_id BIGINT NOT_NULL FOREIGN KEY
             * @member
             * @type {number | null | undefined}
             */
            this["gender_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["race_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["occupation_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["alignment_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["status_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Foreign Keys for World Locations & Factions
             * @member
             * @type {number | null | undefined}
             */
            this["affiliation_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["faction_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["birthplace_location_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["current_location_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * GORM Association
             * Other example for me and the smooth brain : Gender *Gender = (in SQL) LEFT JOIN genders on genders.id = characters.gender_id
             * @member
             * @type {Gender | null | undefined}
             */
            this["gender"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Race | null | undefined}
             */
            this["race"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Occupation | null | undefined}
             */
            this["occupation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Alignment | null | undefined}
             */
            this["alignment"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Status | null | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Affiliation | null | undefined}
             */
            this["affiliation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Faction | null | undefined}
             */
            this["faction"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Location | null | undefined}
             */
            this["birthplace"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Location | null | undefined}
             */
            this["current_location"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Separate Many-to-Many Categories
             * @member
             * @type {PersonalityTrait[] | undefined}
             */
            this["personality_traits"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Strength[] | undefined}
             */
            this["strengths"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Flaw[] | undefined}
             */
            this["flaws"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Weakness[] | undefined}
             */
            this["weaknesses"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Fear[] | undefined}
             */
            this["fears"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Lore & Character Relationships (Populated via Queries)
             * @member
             * @type {Relationship[] | undefined}
             */
            this["relationships"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Lore[] | undefined}
             */
            this["backstories"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Character instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Character}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $Create.ByteSlice;
        const $$createField18_0 = $$createType3;
        const $$createField19_0 = $$createType5;
        const $$createField20_0 = $$createType7;
        const $$createField21_0 = $$createType9;
        const $$createField22_0 = $$createType11;
        const $$createField23_0 = $$createType13;
        const $$createField24_0 = $$createType1;
        const $$createField25_0 = $$createType15;
        const $$createField26_0 = $$createType15;
        const $$createField27_0 = $$createType17;
        const $$createField28_0 = $$createType19;
        const $$createField29_0 = $$createType21;
        const $$createField30_0 = $$createType23;
        const $$createField31_0 = $$createType25;
        const $$createField32_0 = $$createType27;
        const $$createField33_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("portrait" in $$parsedSource) {
            $$parsedSource["portrait"] = $$createField7_0($$parsedSource["portrait"]);
        }
        if ("gender" in $$parsedSource) {
            $$parsedSource["gender"] = $$createField18_0($$parsedSource["gender"]);
        }
        if ("race" in $$parsedSource) {
            $$parsedSource["race"] = $$createField19_0($$parsedSource["race"]);
        }
        if ("occupation" in $$parsedSource) {
            $$parsedSource["occupation"] = $$createField20_0($$parsedSource["occupation"]);
        }
        if ("alignment" in $$parsedSource) {
            $$parsedSource["alignment"] = $$createField21_0($$parsedSource["alignment"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField22_0($$parsedSource["status"]);
        }
        if ("affiliation" in $$parsedSource) {
            $$parsedSource["affiliation"] = $$createField23_0($$parsedSource["affiliation"]);
        }
        if ("faction" in $$parsedSource) {
            $$parsedSource["faction"] = $$createField24_0($$parsedSource["faction"]);
        }
        if ("birthplace" in $$parsedSource) {
            $$parsedSource["birthplace"] = $$createField25_0($$parsedSource["birthplace"]);
        }
        if ("current_location" in $$parsedSource) {
            $$parsedSource["current_location"] = $$createField26_0($$parsedSource["current_location"]);
        }
        if ("personality_traits" in $$parsedSource) {
            $$parsedSource["personality_traits"] = $$createField27_0($$parsedSource["personality_traits"]);
        }
        if ("strengths" in $$parsedSource) {
            $$parsedSource["strengths"] = $$createField28_0($$parsedSource["strengths"]);
        }
        if ("flaws" in $$parsedSource) {
            $$parsedSource["flaws"] = $$createField29_0($$parsedSource["flaws"]);
        }
        if ("weaknesses" in $$parsedSource) {
            $$parsedSource["weaknesses"] = $$createField30_0($$parsedSource["weaknesses"]);
        }
        if ("fears" in $$parsedSource) {
            $$parsedSource["fears"] = $$createField31_0($$parsedSource["fears"]);
        }
        if ("relationships" in $$parsedSource) {
            $$parsedSource["relationships"] = $$createField32_0($$parsedSource["relationships"]);
        }
        if ("backstories" in $$parsedSource) {
            $$parsedSource["backstories"] = $$createField33_0($$parsedSource["backstories"]);
        }
        return new Character(/** @type {Partial<Character>} */($$parsedSource));
    }
}

export class Faction {
    /**
     * Creates a new Faction instance.
     * @param {Partial<Faction>} [$$source = {}] - The source object to create the Faction.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Faction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Faction}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Faction(/** @type {Partial<Faction>} */($$parsedSource));
    }
}

export class Fear {
    /**
     * Creates a new Fear instance.
     * @param {Partial<Fear>} [$$source = {}] - The source object to create the Fear.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fear instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Fear}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fear(/** @type {Partial<Fear>} */($$parsedSource));
    }
}

export class Flaw {
    /**
     * Creates a new Flaw instance.
     * @param {Partial<Flaw>} [$$source = {}] - The source object to create the Flaw.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Flaw instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Flaw}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Flaw(/** @type {Partial<Flaw>} */($$parsedSource));
    }
}

export class Gender {
    /**
     * Creates a new Gender instance.
     * @param {Partial<Gender>} [$$source = {}] - The source object to create the Gender.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Gender instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Gender}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Gender(/** @type {Partial<Gender>} */($$parsedSource));
    }
}

export class Location {
    /**
     * Creates a new Location instance.
     * @param {Partial<Location>} [$$source = {}] - The source object to create the Location.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subtype"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["parent_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Location | null | undefined}
             */
            this["parent"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Location[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Location instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Location}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType15;
        const $$createField7_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parent" in $$parsedSource) {
            $$parsedSource["parent"] = $$createField6_0($$parsedSource["parent"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new Location(/** @type {Partial<Location>} */($$parsedSource));
    }
}

export class Lore {
    /**
     * Creates a new Lore instance.
     * @param {Partial<Lore>} [$$source = {}] - The source object to create the Lore.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("category_id" in $$source)) {
            /**
             * "Historical Event", "Myth", "Backstory"
             * @member
             * @type {number}
             */
            this["category_id"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Null = General Lore | Non-Null = Character Backstory
             * @member
             * @type {number | null | undefined}
             */
            this["character_id"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["created_at"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {LoreCategory | null | undefined}
             */
            this["lore_category"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Character | null | undefined}
             */
            this["character"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Lore instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Lore}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $Create.DateFromTime;
        const $$createField6_0 = $$createType32;
        const $$createField7_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("created_at" in $$parsedSource) {
            $$parsedSource["created_at"] = $$createField5_0($$parsedSource["created_at"]);
        }
        if ("lore_category" in $$parsedSource) {
            $$parsedSource["lore_category"] = $$createField6_0($$parsedSource["lore_category"]);
        }
        if ("character" in $$parsedSource) {
            $$parsedSource["character"] = $$createField7_0($$parsedSource["character"]);
        }
        return new Lore(/** @type {Partial<Lore>} */($$parsedSource));
    }
}

export class LoreCategory {
    /**
     * Creates a new LoreCategory instance.
     * @param {Partial<LoreCategory>} [$$source = {}] - The source object to create the LoreCategory.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoreCategory instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoreCategory}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoreCategory(/** @type {Partial<LoreCategory>} */($$parsedSource));
    }
}

export class Occupation {
    /**
     * Creates a new Occupation instance.
     * @param {Partial<Occupation>} [$$source = {}] - The source object to create the Occupation.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Occupation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Occupation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Occupation(/** @type {Partial<Occupation>} */($$parsedSource));
    }
}

export class PersonalityTrait {
    /**
     * Creates a new PersonalityTrait instance.
     * @param {Partial<PersonalityTrait>} [$$source = {}] - The source object to create the PersonalityTrait.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersonalityTrait instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PersonalityTrait}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PersonalityTrait(/** @type {Partial<PersonalityTrait>} */($$parsedSource));
    }
}

export class Race {
    /**
     * Creates a new Race instance.
     * @param {Partial<Race>} [$$source = {}] - The source object to create the Race.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Race instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Race}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Race(/** @type {Partial<Race>} */($$parsedSource));
    }
}

export class Relationship {
    /**
     * Creates a new Relationship instance.
     * @param {Partial<Relationship>} [$$source = {}] - The source object to create the Relationship.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("source_char_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["source_char_id"] = 0;
        }
        if (!("target_char_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["target_char_id"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * "Companion", "Rival", "Parent", "Lover", "Enemy"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional context/details
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Character | null | undefined}
             */
            this["source_character"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Character | null | undefined}
             */
            this["target_character"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Relationship instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Relationship}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType34;
        const $$createField6_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source_character" in $$parsedSource) {
            $$parsedSource["source_character"] = $$createField5_0($$parsedSource["source_character"]);
        }
        if ("target_character" in $$parsedSource) {
            $$parsedSource["target_character"] = $$createField6_0($$parsedSource["target_character"]);
        }
        return new Relationship(/** @type {Partial<Relationship>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

export class Strength {
    /**
     * Creates a new Strength instance.
     * @param {Partial<Strength>} [$$source = {}] - The source object to create the Strength.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Strength instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Strength}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Strength(/** @type {Partial<Strength>} */($$parsedSource));
    }
}

export class Weakness {
    /**
     * Creates a new Weakness instance.
     * @param {Partial<Weakness>} [$$source = {}] - The source object to create the Weakness.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Weakness instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Weakness}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Weakness(/** @type {Partial<Weakness>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Faction.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Gender.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = Race.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = Occupation.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = Alignment.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = Status.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = Affiliation.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = Location.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = PersonalityTrait.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = Strength.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = Flaw.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = Weakness.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = Fear.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = Relationship.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = Lore.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $Create.Array($$createType14);
const $$createType31 = LoreCategory.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = Character.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
