// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export class FactionDetails {
    /**
     * Creates a new FactionDetails instance.
     * @param {Partial<FactionDetails>} [$$source = {}] - The source object to create the FactionDetails.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("affiliations" in $$source)) {
            /**
             * @member
             * @type {models$0.Affiliation[]}
             */
            this["affiliations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FactionDetails instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FactionDetails}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("affiliations" in $$parsedSource) {
            $$parsedSource["affiliations"] = $$createField3_0($$parsedSource["affiliations"]);
        }
        return new FactionDetails(/** @type {Partial<FactionDetails>} */($$parsedSource));
    }
}

export class LookupItem {
    /**
     * Creates a new LookupItem instance.
     * @param {Partial<LookupItem>} [$$source = {}] - The source object to create the LookupItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LookupItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LookupItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LookupItem(/** @type {Partial<LookupItem>} */($$parsedSource));
    }
}

export class TraitItem {
    /**
     * Creates a new TraitItem instance.
     * @param {Partial<TraitItem>} [$$source = {}] - The source object to create the TraitItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraitItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TraitItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TraitItem(/** @type {Partial<TraitItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = models$0.Affiliation.createFrom;
const $$createType1 = $Create.Array($$createType0);
