// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LookupItem {
    /**
     * Creates a new LookupItem instance.
     * @param {Partial<LookupItem>} [$$source = {}] - The source object to create the LookupItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LookupItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LookupItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LookupItem(/** @type {Partial<LookupItem>} */($$parsedSource));
    }
}

export class TraitItem {
    /**
     * Creates a new TraitItem instance.
     * @param {Partial<TraitItem>} [$$source = {}] - The source object to create the TraitItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraitItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TraitItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TraitItem(/** @type {Partial<TraitItem>} */($$parsedSource));
    }
}
