// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function CreateArticle(arg1:string,arg2:string):Promise<models.Article>;

export function CreateLookup(arg1:string,arg2:string):Promise<services.LookupItem>;

export function CreateTrait(arg1:string,arg2:string):Promise<services.TraitItem>;

export function DeleteAffiliation(arg1:number):Promise<void>;

export function DeleteArticle(arg1:number):Promise<void>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function DeleteFaction(arg1:number):Promise<void>;

export function DeleteLocation(arg1:number):Promise<void>;

export function DeleteLookup(arg1:number,arg2:string):Promise<void>;

export function DeleteLore(arg1:number):Promise<void>;

export function DeleteLoreCategory(arg1:number):Promise<void>;

export function DeleteRelationship(arg1:number):Promise<void>;

export function DeleteTrait(arg1:string,arg2:number):Promise<void>;

export function FetchAffiliation(arg1:number):Promise<models.Affiliation>;

export function FetchAllAffiliations():Promise<Array<models.Affiliation>>;

export function FetchAllArticles():Promise<Array<models.Article>>;

export function FetchAllCharacters(arg1:number):Promise<Array<models.Character>>;

export function FetchAllFactions():Promise<Array<models.Faction>>;

export function FetchAllLocations():Promise<Array<models.Location>>;

export function FetchAllLookup(arg1:string):Promise<Array<services.LookupItem>>;

export function FetchAllLore():Promise<Array<models.Lore>>;

export function FetchAllTraits(arg1:string):Promise<Array<services.TraitItem>>;

export function FetchArticle(arg1:number):Promise<models.Article>;

export function FetchCategories():Promise<Array<models.LoreCategory>>;

export function FetchCharacter(arg1:number):Promise<models.Character>;

export function FetchCharacterLore(arg1:number):Promise<Array<models.Lore>>;

export function FetchCharacterRelationships(arg1:number):Promise<Array<models.Relationship>>;

export function FetchFaction(arg1:number):Promise<models.Faction>;

export function FetchGeneralLore():Promise<Array<models.Lore>>;

export function FetchLocation(arg1:number):Promise<models.Location>;

export function FetchLookup(arg1:number,arg2:string):Promise<services.LookupItem>;

export function FetchLore(arg1:number):Promise<models.Lore>;

export function FetchLoreByCategory(arg1:number):Promise<Array<models.Lore>>;

export function FetchRelationship(arg1:number):Promise<models.Relationship>;

export function FetchTopLevelLocations():Promise<Array<models.Location>>;

export function FetchTrait(arg1:string,arg2:number):Promise<services.TraitItem>;

export function Greet(arg1:string):Promise<string>;

export function SaveAffiliation(arg1:models.Affiliation):Promise<models.Affiliation>;

export function SaveCharacter(arg1:models.Character):Promise<models.Character>;

export function SaveFaction(arg1:models.Faction):Promise<models.Faction>;

export function SaveLocation(arg1:models.Location):Promise<models.Location>;

export function SaveLookup(arg1:number,arg2:string,arg3:string):Promise<services.LookupItem>;

export function SaveLore(arg1:models.Lore):Promise<models.Lore>;

export function SaveLoreCategory(arg1:number,arg2:string):Promise<models.LoreCategory>;

export function SaveRelationships(arg1:models.Relationship):Promise<models.Relationship>;

export function SaveTrait(arg1:number,arg2:string,arg3:string):Promise<services.TraitItem>;

export function UpdateArticle(arg1:number,arg2:string,arg3:string):Promise<models.Article>;
