// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateArticle(arg1, arg2) {
  return window['go']['main']['App']['CreateArticle'](arg1, arg2);
}

export function CreateLookup(arg1, arg2) {
  return window['go']['main']['App']['CreateLookup'](arg1, arg2);
}

export function CreateTrait(arg1, arg2) {
  return window['go']['main']['App']['CreateTrait'](arg1, arg2);
}

export function DeleteAffiliation(arg1) {
  return window['go']['main']['App']['DeleteAffiliation'](arg1);
}

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteFaction(arg1) {
  return window['go']['main']['App']['DeleteFaction'](arg1);
}

export function DeleteLocation(arg1) {
  return window['go']['main']['App']['DeleteLocation'](arg1);
}

export function DeleteLookup(arg1, arg2) {
  return window['go']['main']['App']['DeleteLookup'](arg1, arg2);
}

export function DeleteLore(arg1) {
  return window['go']['main']['App']['DeleteLore'](arg1);
}

export function DeleteLoreCategory(arg1) {
  return window['go']['main']['App']['DeleteLoreCategory'](arg1);
}

export function DeleteRelationship(arg1) {
  return window['go']['main']['App']['DeleteRelationship'](arg1);
}

export function DeleteTrait(arg1, arg2) {
  return window['go']['main']['App']['DeleteTrait'](arg1, arg2);
}

export function FetchAffiliation(arg1) {
  return window['go']['main']['App']['FetchAffiliation'](arg1);
}

export function FetchAllAffiliations() {
  return window['go']['main']['App']['FetchAllAffiliations']();
}

export function FetchAllArticles() {
  return window['go']['main']['App']['FetchAllArticles']();
}

export function FetchAllCharacters(arg1) {
  return window['go']['main']['App']['FetchAllCharacters'](arg1);
}

export function FetchAllFactions() {
  return window['go']['main']['App']['FetchAllFactions']();
}

export function FetchAllLocations() {
  return window['go']['main']['App']['FetchAllLocations']();
}

export function FetchAllLookup(arg1) {
  return window['go']['main']['App']['FetchAllLookup'](arg1);
}

export function FetchAllLore() {
  return window['go']['main']['App']['FetchAllLore']();
}

export function FetchAllTraits(arg1) {
  return window['go']['main']['App']['FetchAllTraits'](arg1);
}

export function FetchArticle(arg1) {
  return window['go']['main']['App']['FetchArticle'](arg1);
}

export function FetchCategories() {
  return window['go']['main']['App']['FetchCategories']();
}

export function FetchCharacter(arg1) {
  return window['go']['main']['App']['FetchCharacter'](arg1);
}

export function FetchCharacterLore(arg1) {
  return window['go']['main']['App']['FetchCharacterLore'](arg1);
}

export function FetchCharacterRelationships(arg1) {
  return window['go']['main']['App']['FetchCharacterRelationships'](arg1);
}

export function FetchFaction(arg1) {
  return window['go']['main']['App']['FetchFaction'](arg1);
}

export function FetchGeneralLore() {
  return window['go']['main']['App']['FetchGeneralLore']();
}

export function FetchLocation(arg1) {
  return window['go']['main']['App']['FetchLocation'](arg1);
}

export function FetchLookup(arg1, arg2) {
  return window['go']['main']['App']['FetchLookup'](arg1, arg2);
}

export function FetchLore(arg1) {
  return window['go']['main']['App']['FetchLore'](arg1);
}

export function FetchLoreByCategory(arg1) {
  return window['go']['main']['App']['FetchLoreByCategory'](arg1);
}

export function FetchRelationship(arg1) {
  return window['go']['main']['App']['FetchRelationship'](arg1);
}

export function FetchTopLevelLocations() {
  return window['go']['main']['App']['FetchTopLevelLocations']();
}

export function FetchTrait(arg1, arg2) {
  return window['go']['main']['App']['FetchTrait'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveAffiliation(arg1) {
  return window['go']['main']['App']['SaveAffiliation'](arg1);
}

export function SaveCharacter(arg1) {
  return window['go']['main']['App']['SaveCharacter'](arg1);
}

export function SaveFaction(arg1) {
  return window['go']['main']['App']['SaveFaction'](arg1);
}

export function SaveLocation(arg1) {
  return window['go']['main']['App']['SaveLocation'](arg1);
}

export function SaveLookup(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLookup'](arg1, arg2, arg3);
}

export function SaveLore(arg1) {
  return window['go']['main']['App']['SaveLore'](arg1);
}

export function SaveLoreCategory(arg1, arg2) {
  return window['go']['main']['App']['SaveLoreCategory'](arg1, arg2);
}

export function SaveRelationships(arg1) {
  return window['go']['main']['App']['SaveRelationships'](arg1);
}

export function SaveTrait(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTrait'](arg1, arg2, arg3);
}

export function UpdateArticle(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateArticle'](arg1, arg2, arg3);
}
